# This file contains the global app configuration.
---
ntfy:
  # The ntfy server hosting your topic.
  server: 'https://ntfy.sh'
  # The topic to publish notifications to.
  topic: ''
  # Optional: needed only if the topic is access-controlled.
  token: ''
chrome:
  # Path to your Chrome executable.
  # e.g. C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
  # or /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
  path: ''
  # Any arguments to open Chrome with.
  # e.g. ['--profile-directory=Profile 1'] to use a different profile
  args: []
